apiVersion: v1
kind: Pod
metadata:
  name: postgres-app
  labels:
    name: postgres-app-pod
    app: demo-voting-app

spec:
  containers:
    - name:  postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432