apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting

spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-app-pod
    app: demo-voting-app